import React from 'react'
import './Header.css'

function Header() {
  return (
    <header className='Header'>
      <div>Each new term in the Fibonacci sequence is generated by adding the previous two terms.</div>
      <div>By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</div>
      <h4>Task : By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</h4>
    </header>
  )
}

export default Header;